### ISSUE TITLE
getItemPosition() 方法的调用问题

### ISSUE THREAD

**Issue by 900326** [li504799868/FlycoTabLayoutZ#12]
一般都是使用viewpager+fragment+FragmentPagerAdapter,但是FragmentPagerAdapter里面如果复写getItemPosition()方法,要怎么写

**Comment by li504799868** [comment]
我在demo的做法是 ： 给Fragment的rootView添加一个position的tag，然后在getItemPosition中得到这个position的tag。
这种做法确实不太好，我已经找到更简单的方法，近期会做一些修改。

**Comment by li504799868** [comment]
老铁，新版本已经发布，可以更新试试，不用重写getItemPosition方法了
