### ISSUE TITLE
在项目里加入gradle dependencies 后出现link error

### ISSUE THREAD

**Issue by dinghaoz** [li504799868/FlycoTabLayoutZ#15]
![Screen Shot 2020-07-19 at 10 21 17 AM](https://user-images.githubusercontent.com/26001134/87866177-106a0780-c9b1-11ea-9a47-f18baf9f123f.png)
![Screen Shot 2020-07-19 at 10 21 14 AM](https://user-images.githubusercontent.com/26001134/87866179-1364f800-c9b1-11ea-99f1-78cf22a8bf9d.png)

**Comment by li504799868** [comment]
不知道为什么，图刷新不出来，你试着加上

 https://dl.bintray.com/lizp/maven

看看能不能解决问题

**Comment by li504799868** [comment]
![image](https://user-images.githubusercontent.com/20336720/87899485-eb929480-ca83-11ea-84f5-144297501b3c.png)

**Comment by li504799868** [comment]
修改成新的属性吧，之前的属性和动画效果有一点兼容问题

**Comment by dinghaoz** [comment]
使用的时候改成新属性了，但是还是有这个link错误。不好意思，没有描述清楚
你可以试试新建一个项目，然后在gradle dependencies 里加入  implementation 'com.lzp:FlycoTabLayoutZ:1.2.2' 。编译就出错了。这是时候代码里还没有开始用 FlycoTabLayoutZ，仅仅是加入了dependencies。这个issue 不能reopen，我再开一个，再描述清楚些啊
