### ISSUE TITLE
SlidingScaleTabLayoutFragmentActivity 的tab 标题改成英文后大小异常

### ISSUE THREAD

**Issue by dinghaoz** [li504799868/FlycoTabLayoutZ#16]
![middle_img_4e682014-2516-433b-87cd-9813999ae72g](https://user-images.githubusercontent.com/26001134/87866197-4909e100-c9b1-11ea-8c24-6293185907fc.png)

**Comment by li504799868** [comment]
感谢老铁的反馈，该问题已修复，可以更新一下1.2.2。
