### ISSUE TITLE
加入dependency后编译出现Link Error

### ISSUE THREAD

**Issue by dinghaoz** [li504799868/FlycoTabLayoutZ#17]
新建一个项目，然后在gradle dependencies 里加入  implementation 'com.lzp:FlycoTabLayoutZ:1.2.2' 。编译就出错。这个时候代码里还没有开始用 FlycoTabLayoutZ，仅仅是加入了dependencies。

![Screen Shot 2020-07-19 at 10 21 17 AM](https://user-images.githubusercontent.com/26001134/88006746-f9f1b680-cb3e-11ea-97af-176420c5cdf8.png)
![Screen Shot 2020-07-19 at 10 21 14 AM](https://user-images.githubusercontent.com/26001134/88006751-fbbb7a00-cb3e-11ea-8a4e-db00bed922bf.png)

**Comment by li504799868** [comment]
该问题修复，老铁可以更新一下v1.2.3试一试。

**Comment by dinghaoz** [comment]
1.2.3好像还没有发布到 maven?  
<img width="1098" alt="Screen Shot 2020-07-21 at 1 47 38 PM" src="https://user-images.githubusercontent.com/26001134/88017705-cc196b80-cb58-11ea-9336-4f994775ad3f.png">

**Comment by li504799868** [comment]
再试一下，上午好像没发布成功……
