### ISSUE TITLE
红点默认位置不在右上角

### ISSUE THREAD

**Issue by dinghaoz** [li504799868/FlycoTabLayoutZ#18]
![middle_img_9b99c888-4f4c-449f-8655-7e0109fd829g](https://user-images.githubusercontent.com/26001134/88007111-d0855a80-cb3f-11ea-92df-8413b3572208.png)

只调用了，没有改任何东西。能把红点的默认位置设为右上角吗？谢谢老铁提供这么好用的组件，且回复及时，已经决定在项目里正式用了。
`tabLayout.showDot(2);`

**Comment by li504799868** [comment]
红点位置已修复，老铁可以更新一下v1.2.3试一试。

**Comment by dinghaoz** [comment]
验过已修复
