### ISSUE TITLE
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.

### ISSUE THREAD

**Issue by pumu97** [li504799868/FlycoTabLayoutZ#2]
demo运行时报错

WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: FlycoTabLayout_Lib

grdle版本:
com.android.tools.build:gradle:3.3.1
distributionUrl=https://services.gradle.org/distributions/gradle-4.10.1-all.zip

**Comment by li504799868** [comment]
这个是一个警告，好像是我发布jCenter的插件报的警告，我之后会把他改掉，3Q
