### ISSUE TITLE
title大小切换效果没有

### ISSUE THREAD

**Issue by szxv587** [li504799868/FlycoTabLayoutZ#7]
直接复制你xml的控制设置的

**Comment by dapanjimianpaigumian** [comment]
我也遇到这个问题了，字体大小切换没有效果

**Comment by dapanjimianpaigumian** [comment]
我知道为啥无效了，我没有复写FragmentPagerAdapter 的 getItemPosition方法。

**Comment by li504799868** [comment]
新版本已经给不需要在重写getItemPosition方法了，老铁可以更新一下。
