### ISSUE TITLE
有没有可以横向滑动，没有ViewPager的tab？

### ISSUE THREAD

**Issue by 921668753** [li504799868/FlycoTabLayoutZ#8]
有没有可以横向滑动，没有ViewPager的tab？

**Comment by li504799868** [comment]
这个我还真不清楚，你可以自己拷贝一份代码，稍微做一点修改

**Comment by li504799868** [comment]
1.3.1版本SlidingScaleTabLayout 可以单独使用了，老铁可以看一下Demo。
